import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'User Guide',
      link: { type: 'generated-index', title: 'User Guide', slug: '/user-guide' },
      items: [{ type: 'autogenerated', dirName: 'user-guide' }],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      link: { type: 'generated-index', title: 'Developer Guide', slug: '/developer-guide' },
      items: [{ type: 'autogenerated', dirName: 'developer-guide' }],
    },
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'generated-index', title: 'Reference', slug: '/reference' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'generated-index', title: 'API Reference', slug: '/api' },
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: { type: 'generated-index', title: 'Tutorials', slug: '/tutorials' },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
  ],
};

export default sidebars;
