name: CI - Assets Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-assets:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read pnpm version from package.json
        id: pnpm-version
        run: >
          node -e "const v=require('./package.json').packageManager.split('@')[1];
          require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `pnpm_version=${v}\n`);"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.pnpm_version }}
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate assets
        run: pnpm run validate:assets


