name: CI - Lighthouse + Axe

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build app
        run: pnpm run build
        env:
          VITE_MAP_STYLE_URL: /styles/blank.json

      - name: Install Lighthouse
        run: pnpm dlx -y @lhci/cli@0.12.x install

      - name: Start preview server
        run: pnpm run preview -- --host --port 4173 &

      - name: Wait for preview
        run: |
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:4173 > /dev/null; then exit 0; fi
            sleep 1
          done
          echo "Preview server did not become ready" >&2
          exit 1

      - name: Run Lighthouse CI (collect + assert only)
        run: |
          pnpm dlx -y @lhci/cli@0.12.x collect --url=http://127.0.0.1:4173/
          pnpm dlx -y @lhci/cli@0.12.x assert --preset=lighthouse:recommended

      - name: Upload LHCI results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci


