name: CI - Vitest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.1
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run unit tests (Vitest) with coverage
        run: pnpm -s test:unit -- --reporter=dot

      - name: Upload coverage (LCOV)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-coverage-lcov
          path: |
            coverage/lcov.info
            coverage/lcov-report


